export const ESPECIALIDADES = [
  'Acompañamiento Terapéutico',
  'Cardiología',
  'Cosmetología',
  'Clínica Médica',
  'Dermatología',
  'Endocrinología',
  'Esteticista',
  'Estimulación Temprana',
  'Fisiatría',
  'Fonoaudiología',
  'Gastroenterología',
  'Ginecología y Obstetricia',
  'Kinesiología',
  'Medicina de Familia',
  'Musicoterapia',
  'Neurología',
  'Neuropsicología',
  'Nutrición',
  'Odontología',
  'Pediatría',
  'Psicología',
  'Psicopedagogía',
  'Psiquiatría',
  'Psiquiatría Infanto-Juvenil',
  'Secretariado Médico',
  'Terapia Ocupacional',
  'Traumatología',
  'Urología',
  'Otro / No listado',
]
